openapi: 3.0.0
info:
  title: Euodia API
  version: "1.0.0"
  description: API documentation for Euodia application
servers:
  - url: "https://student-food-be.onrender.com/"
    description: Development server
components:
  schemas:
    Category:
      type: object
      properties:
        _id:
          type: string
          description: The ID of the category
        title:
          type: string
          description: The title of the category
        description:
          type: string
          description: The description of the category
        slug:
          type: object
          properties:
            current:
              type: string
              description: The current slug of the category

components:
  schemas:
    Dish:
      type: object
      required:
        - title
        - description
        - price
        - category
        - image
        - status
        - sortOrder
      properties:
        _id:
          type: string
          description: Auto-generated ID of the dish
        title:
          type: string
          description: The name of the dish
        description:
          type: string
          description: A brief description of the dish
        price:
          type: number
          description: Price of the dish
        category:
          type: string
        image:
          type: string
        status:
          type: boolean
          description: Availability status of the dish
        sortOrder:
          type: number
          description: Sorting order of the dish